# Generated by Django 2.0.7 on 2018-07-10 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('b_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'site_data',
            },
        ),
        migrations.CreateModel(
            name='SiteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'site',
            },
        ),
        migrations.AddField(
            model_name='sitedatamodel',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_data', to='sites.SiteModel'),
        ),
    ]
