# Generated by Django 2.0.7 on 2018-07-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedatamodel',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
